# AI - Project
Muhammad Fateh Tariq - FA17_BSCS-019 | 
Asad Ali Hasani - FA17_BSCS-020 | 
Osama Syed - FA17_BSCS-069 | 
Salman Ahmed - FA17_BSCS-082

In [ ]:
import math as mt
import pandas as pd
import numpy as np
import copy as copy
import sklearn.metrics

In [ ]:
StudentInfo = pd.read_excel('Book1.xlsx')
print('Student Info: ')

print(StudentInfo)


arr = StudentInfo.to_numpy()
arrT = np.transpose(arr)

print('\n' + str(arr))

Student Info: 
   English  Maths  Physics  Chemistry  Computers Science  Urdu  Pak.Studies
0       40     11        0          4                 37    22           44
1       30     40       18         18                  0    11            0
2       50      0       50          9                 41    54           32
3       20     35       41          0                 18    21           41
4        0     42       47         28                 20    44           43
5       28     10       28         33                  0    55           12
6       33     22       11         43                 53     0           33

[[40 11  0  4 37 22 44]
 [30 40 18 18  0 11  0]
 [50  0 50  9 41 54 32]
 [20 35 41  0 18 21 41]
 [ 0 42 47 28 20 44 43]
 [28 10 28 33  0 55 12]
 [33 22 11 43 53  0 33]]


# Similarity Functions

In [ ]:
def cosineDeff(v1, v2):
    aIntob = 0
    aSquare = 0
    bSquare = 0

    if(len(v1) == len(v2)):
        for i in range(len(v1)):
            aIntob += v1[i] * v2[i]
            aSquare += v1[i] * v1[i]
            bSquare += v2[i] * v2[i]

    return aIntob / (mt.sqrt(aSquare) * mt.sqrt(bSquare))

def AvgCossimDeff(v1, v2):
    aIntob = 0
    aSquare = 0
    bSquare = 0

    if(len(v1) == len(v2)):
        for i in range(len(v1)):
            aIntob += v1[i] * v2[i]
            aSquare += v1[i] * v1[i]
            bSquare += v2[i] * v2[i]

    return aIntob / (mt.sqrt(aSquare) * mt.sqrt(bSquare))

def CencosineDeff(v1, v2, r1, r2):
    aIntob = 0
    aSquare = 0
    bSquare = 0
    newV1 = 0
    newV2 = 0

    if(len(v1) == len(v2)):
        for i in range(len(v1)):
            if (v1[i] != 0):
                newV1 = v1[i]-(r1)
            else:
                newV1 = 0

            if (v2[i] != 0):
                newV2 = v2[i]-(r2)
            else:
                newV2 = 0

            aIntob += newV1 * newV2
            aSquare += newV1 * newV1
            bSquare += newV2 * newV2

    return aIntob / (mt.sqrt(aSquare) * mt.sqrt(bSquare))

def pearsonCorr(v1, v2):

    sum_a = 0
    sum_b = 0
    aIntob = 0
    aSquare = 0
    bSquare = 0
    n = len(v1)
    r = 0

    if(len(v1) == len(v2)):
        for i in range(len(v1)):
            sum_a += v1[i]
            sum_b += v2[i]

            aIntob += v1[i] * v2[i]
            aSquare += v1[i] * v1[i]
            bSquare += v2[i] * v2[i]

    numerator = (n*(aIntob)-(sum_a*sum_b))
    denumerator = mt.sqrt(((n*aSquare)-(sum_a*sum_a))
                          * ((n*bSquare)-(sum_b*sum_b)))

    r = numerator/denumerator
    return r

def listAverage(arr):
    sumN = 0
    lessen = 0
    for n in range(len(arr)):
        if(arr[n] != 0):
            sumN += arr[n]
        else:
            lessen += 1
    return sumN / (len(arr) - lessen)

def CenteredCosimMatrix(arr):
    conresult = []

    for i in range(len(arr)):
        conresult.append([])

    for i in range(len(arr)):
        r1 = listAverage(arr[i])

        for k in range(i, len(arr)):
            r2 = listAverage(arr[k])

            r3 = CencosineDeff(arr[i], arr[k], r1, r2)

            conresult[i].append(r3)
            if(i != k):
                conresult[k].append(r3)
    return conresult

def AvgCossimMatrix(arr):
    cenresult = []
    for i in arr:
        cenresult.append([])

    for i in range(len(arr)):
        avg = listAverage(arr[i])

        for j in range(i, len(arr)):
            avg0 = listAverage(arr[j])
            arr1 = copy.deepcopy(arr[i])
            arr2 = copy.deepcopy(arr[j])
            for x in range(len(arr)):
                if(mt.isnan(arr1[x])):
                    arr1[x] = avg

                if(mt.isnan(arr2[x])):
                    arr2[x] = avg0

            r = AvgCossimDeff(arr1, arr2)
            cenresult[i].append(r)
            if(i != j):
                cenresult[j].append(r)
    return cenresult

def PearMatrix(arr):
    peresult = []
    for i in range(len(arr)):
        peresult.append([])
    for i in range(len(arr)):
        for j in range(i, len(arr)):
            r = pearsonCorr(arr[i], arr[j])
            peresult[i].append(r)
            if(i != j):
                peresult[j].append(r)
    return peresult

def simFunc(arr1, arr2):
    result = cosineDeff(arr1, arr2)
    return result

def simMatrix(arr):
    result = []
    for i in range(len(arr)):
        result.append([])
    for i in range(len(arr)):
        for j in range(i, len(arr)):
            r = simFunc(arr[i], arr[j])
            result[i].append(r)
            if(i != j):
                result[j].append(r)
    return result



In [ ]:
result = simMatrix(arr)
cenresult = AvgCossimMatrix(arr)
conresult = CenteredCosimMatrix(arr)
peresult = PearMatrix(arr)

# Similarity Matrix

In [ ]:
print('')
print('cosine similarity Matrix: ')
print(np.array(result))
print('')
print('Avg Consin Matrix: ')
print(np.array(cenresult))
print('')
print('Centered Consin Matrix: ')
print(np.array(conresult))
print('')
print('Pearson Matrix: ')
print(np.array(peresult))
print('')


cosine similarity Matrix: 
[[1.         0.45973933 0.79958857 0.73024062 0.59378561 0.5417207
  0.80266269]
 [0.45973933 1.         0.53357695 0.68468892 0.64994553 0.66865482
  0.57623676]
 [0.79958857 0.53357695 1.         0.79455668 0.73335046 0.81005358
  0.65174285]
 [0.73024062 0.68468892 0.79455668 1.         0.89852209 0.63459691
  0.64014975]
 [0.59378561 0.64994553 0.73335046 0.89852209 1.         0.76874012
  0.62816847]
 [0.5417207  0.66865482 0.81005358 0.63459691 0.76874012 1.
  0.4919859 ]
 [0.80266269 0.57623676 0.65174285 0.64014975 0.62816847 0.4919859
  1.        ]]

Avg Consin Matrix: 
[[1.         0.45973933 0.79958857 0.73024062 0.59378561 0.5417207
  0.80266269]
 [0.45973933 1.         0.53357695 0.68468892 0.64994553 0.66865482
  0.57623676]
 [0.79958857 0.53357695 1.         0.79455668 0.73335046 0.81005358
  0.65174285]
 [0.73024062 0.68468892 0.79455668 1.         0.89852209 0.63459691
  0.64014975]
 [0.59378561 0.64994553 0.73335046 0.89852209 1.         0.

In [ ]:
def average2(v1, v2):
    return (v1 + v2) / 2


def average3(v1, v2, v3):
    return (v1 + v2 + v3) / 3


def average4(v1, v2, v3, v4):
    return (v1 + v2 + v3 + v4) / 4

In [ ]:
result = simMatrix(arr)

In [ ]:
def sortedMatrix(result):
    rs = []
    for i in result:
        i.sort(reverse=True)
        rs.append(i)
    return rs

# Sorted Indices Matrix

In [ ]:
key = []
for i in result:
    key.append(sorted(range(len(i)), reverse=True, key=lambda k: i[k]))
key = np.array(key)

pkey = []
for i in peresult:
    pkey.append(sorted(range(len(i)), reverse=True, key=lambda k: i[k]))
pkey = np.array(pkey)

In [ ]:
print('Indices Cosine Matrix: ')
print(key)
print('')

print('Indices Pearson Matrix: ')
print(pkey)
print('')

Indices Cosine Matrix: 
[[0 6 2 3 4 5 1]
 [1 3 5 4 6 2 0]
 [2 5 0 3 4 6 1]
 [3 4 2 0 1 6 5]
 [4 3 5 2 1 6 0]
 [5 2 4 1 3 0 6]
 [6 0 2 3 4 1 5]]

Indices Pearson Matrix: 
[[0 6 2 3 5 1 4]
 [1 5 3 4 6 2 0]
 [2 5 0 3 4 6 1]
 [3 4 2 0 1 5 6]
 [4 3 5 1 2 0 6]
 [5 2 4 1 3 0 6]
 [6 0 1 2 3 4 5]]



In [ ]:
sortedArr = sortedMatrix(result)
sortedArrP = sortedMatrix(peresult)

sortedArr2 = np.array(sortedArr)
sortedArrP2 = np.array(sortedArrP)

In [ ]:
print('Similarity Indices Cosine Matrix: ')
print(sortedArr2)
print("")
print('Similarity Indices Pearson Matrix: ')
print(sortedArrP2)

Similarity Indices Cosine Matrix: 
[[1.         0.80266269 0.79958857 0.73024062 0.59378561 0.5417207
  0.45973933]
 [1.         0.68468892 0.66865482 0.64994553 0.57623676 0.53357695
  0.45973933]
 [1.         0.81005358 0.79958857 0.79455668 0.73335046 0.65174285
  0.53357695]
 [1.         0.89852209 0.79455668 0.73024062 0.68468892 0.64014975
  0.63459691]
 [1.         0.89852209 0.76874012 0.73335046 0.64994553 0.62816847
  0.59378561]
 [1.         0.81005358 0.76874012 0.66865482 0.63459691 0.5417207
  0.4919859 ]
 [1.         0.80266269 0.65174285 0.64014975 0.62816847 0.57623676
  0.4919859 ]]

Similarity Indices Pearson Matrix: 
[[ 1.          0.37576675  0.35444254  0.0895663  -0.32760296 -0.42812127
  -0.47303731]
 [ 1.          0.10419536  0.02066903 -0.15067729 -0.25689506 -0.41527208
  -0.42812127]
 [ 1.          0.36560027  0.35444254  0.15733216 -0.17128129 -0.32288902
  -0.41527208]
 [ 1.          0.52925764  0.15733216  0.0895663   0.02066903 -0.28849078
  -0.43785736]

# Weighted Average

In [ ]:
def wAverage(user, num, pridictedIndex):
    similerUser = {}
    for i in range(len(key)):
        if((i + 1) <= num):
            similerUser.update(
                {key[int(user)][i + 1]: sortedArr2[int(user)][i]})
    s = 0
    avgTotal = 0
    weightedAverage = 0

    index = pridictedIndex
    for similerUserKeys in similerUser:
        s += similerUser[similerUserKeys] * arr[similerUserKeys][int(index)]
        avgTotal += similerUser[similerUserKeys]
    weightedAverage = s/avgTotal

    return weightedAverage


def wAverageI(user, num, pridictedIndex):
    similerUser = {}
    for i in range(len(key)):
        if((i + 1) <= num):
            similerUser.update(
                {key[int(user)][i + 1]: sortedArr3[int(user)][i]})
    s = 0
    avgTotal = 0
    weightedAverage = 0

    index = pridictedIndex
    for similerUserKeys in similerUser:
        s += similerUser[similerUserKeys] * arr[similerUserKeys][int(index)]
        avgTotal += similerUser[similerUserKeys]
    weightedAverage = s/avgTotal

    return weightedAverage

def pwAverage(user, num, pridictedIndex):
    similerUser = {}
    for i in range(len(pkey)):
        if((i + 1) <= num):
            similerUser.update(
                {pkey[int(user)][i + 1]: sortedArrP2[int(user)][i]})
    s = 0
    avgTotal = 0
    weightedAverage = 0

    index = pridictedIndex
    for similerUserKeys in similerUser:
        s += similerUser[similerUserKeys] * arr[similerUserKeys][int(index)]
        avgTotal += similerUser[similerUserKeys]
    weightedAverage = s/avgTotal

    return weightedAverage


def pwAverageI(user, num, pridictedIndex):
    similerUser = {}
    for i in range(len(pkey)):
        if((i + 1) <= num):
            similerUser.update(
                {pkey[int(user)][i + 1]: sortedArrP2[int(user)][i]})
    s = 0
    avgTotal = 0
    weightedAverage = 0

    index = pridictedIndex
    for similerUserKeys in similerUser:
        s += similerUser[similerUserKeys] * arr[similerUserKeys][int(index)]
        avgTotal += similerUser[similerUserKeys]
    weightedAverage = s/avgTotal

    return weightedAverage

In [ ]:
def replaceWithW(arr, value, predictedValue):
    arr[predictedValue] = value

In [ ]:
arrCopy = copy.deepcopy(arr)
arrCopy2 = copy.deepcopy(arr)
arrcopym = copy.deepcopy(arr)

def newModel (arr1, arr2):
    i = 0
    for i in range(len(arr1)):
        for j in range(len(arr1)):    
            arrcopym[i][j] = ((arr1[i][j]+arr2[i][j])/2)
    
    return arrcopym

# User to User

4 Similar Users

In [ ]:
#Cosine Method
user = input('Specify the User to reveal similar Users: ')
pridictedValue = input('Specify the index to pridict: ')
print('\n[4] Most Similar Users to User (Cosine method)[' + user+'] are:')
avg = average4(sortedArr2[int(user)][1],
               sortedArr2[int(user)][2], sortedArr2[int(user)][3], sortedArr[int(user)][4])
replaceWithW(arrCopy[int(user)], float(wAverage(user, 4, pridictedValue)), int(pridictedValue))
mse = sklearn.metrics.mean_squared_error(arr[int(user)], arrCopy[int(user)])
rmse = mt.sqrt(mse)
print('[Average]: '+str(float(avg)))
print('[Accuracy]:'+str(100 - rmse)+' RMSE')

for i in range(len(key)):
    if((i + 1) <= 4):
        print('User[' + str(key[int(user)][i + 1])+']')

print('\n[Pridicted missing value through Weighted Average]: ' +
      str(float(wAverage(user, 4, pridictedValue))))

#Pearson Method
user = input('Specify the User to reveal similar Users: ')
pridictedValue = input('Specify the index to pridict: ')
print('\n[4] Most Similar Users to User (Pearson method)[' + user+'] are: ')
avg = average4(sortedArrP2[int(user)][1],
               sortedArrP2[int(user)][2], sortedArrP2[int(user)][3], sortedArrP2[int(user)][4])
replaceWithW(arrCopy2[int(user)], float(pwAverage(user, 4, pridictedValue)), int(pridictedValue))
mse = sklearn.metrics.mean_squared_error(arr[int(user)], arrCopy2[int(user)])
rmse = mt.sqrt(mse)
print('[Average]: '+str(float(avg)))
print('[Accuracy]:'+str(100 - rmse)+' RMSE')

for i in range(len(pkey)):
    if((i + 1) <= 4):
        print('User[' + str(pkey[int(user)][i + 1])+']')

print('\n[Pridicted missing value through Weighted Average]: ' +
      str(float(pwAverage(user, 4, pridictedValue))))

print("New model based after averaging Cosine and Pearson:")
mse = sklearn.metrics.mean_squared_error(arrCopy, arrCopy2)
rmse = mt.sqrt(mse)
print('[Accuracy]:'+str(100 - rmse)+' RMSE')
print(newModel(arrCopy, arrCopy2))
print("")
print("Original:")
print(arrCopy)

Specify the User to reveal similar Users: 0
Specify the index to pridict: 0

[4] Most Similar Users to User (Cosine method)[0] are:
[Average]: 0.7315693746684003
[Accuracy]:94.70849737787081 RMSE
User[6]
User[2]
User[3]
User[4]

[Pridicted missing value through Weighted Average]: 26.74422294789567
Specify the User to reveal similar Users: 0
Specify the index to pridict: 1

[4] Most Similar Users to User (Pearson method)[0] are: 
[Average]: 0.12304315654310233
[Accuracy]:75.0829949059454 RMSE
User[6]
User[2]
User[3]
User[5]

[Pridicted missing value through Weighted Average]: 19.39862911898359
New model based after averaging Cosine and Pearson:
[Accuracy]:77.81386717348158 RMSE
[[33 15 25 12 18 25 38]
 [20 40  9 26 21 10 11]
 [25  9 50 25 44 41 21]
 [12 26 25  0 23 27 42]
 [18 21 44 23 20 22 48]
 [25 10 41 27 22 55  6]
 [38 11 21 42 48  6 33]]

Original:
[[26 11  0  4 37 22 44]
 [30 40 18 18  0 11  0]
 [50  0 50  9 41 54 32]
 [20 35 41  0 18 21 41]
 [ 0 42 47 28 20 44 43]
 [28 10 28 33 

3 Similar Users

In [ ]:
#Cosine Method
user = input('Specify the User to reveal similar Users: ')
pridictedValue = input('Specify the index to pridict: ')

print('\n[3] Most Similar Users to User (Cosine Method) [' + user+'] are:')
avg = average3(sortedArr2[int(user)][1],
               sortedArr2[int(user)][2], sortedArr2[int(user)][3])
replaceWithW(arrCopy[int(user)], float(wAverage(user, 3, pridictedValue)), int(pridictedValue))
mse = sklearn.metrics.mean_squared_error(arr[int(user)], arrCopy[int(user)])
rmse = mt.sqrt(mse)
print('[Average]: '+str(float(avg)))
print('[Accuracy]:'+str(100 - rmse)+' RMSE')

for i in range(len(key)):
    if((i + 1) <= 3):
        print('User[' + str(key[int(user)][i + 1])+']')

print('\n[Pridicted missing value through Weighted Average]: ' +
      str(float(wAverage(user, 3, pridictedValue))))

#Pearson Method
user = input('Specify the User to reveal similar Users: ')
pridictedValue = input('Specify the index to pridict: ')
print('\n[3] Most Similar Users to User (Pearson method) [' + user+'] are: ')
avg = average3(sortedArrP2[int(user)][1],
               sortedArrP2[int(user)][2], sortedArrP2[int(user)][3])
replaceWithW(arrCopy2[int(user)], float(pwAverage(user, 3, pridictedValue)), int(pridictedValue))
mse = sklearn.metrics.mean_squared_error(arr[int(user)], arrCopy2[int(user)])
rmse = mt.sqrt(mse)
print('[Average]: '+str(float(avg)))
print('[Accuracy]:'+str(100 - rmse)+' RMSE')

for i in range(len(pkey)):
    if((i + 1) <= 3):
        print('User[' + str(pkey[int(user)][i + 1])+']')

print('\n[Pridicted missing value through Weighted Average]: ' +
      str(float(pwAverage(user, 3, pridictedValue))))

print("New model based after averaging Cosine and Pearson: ")
mse = sklearn.metrics.mean_squared_error(arrCopy, arrCopy2)
rmse = mt.sqrt(mse)
print('[Accuracy]:'+str(100 - rmse)+' RMSE')
print(newModel(arrCopy, arrCopy2))
print("")
print("Original: ")
print(arrCopy)


Specify the User to reveal similar Users: 0
Specify the index to pridict: 0

[3] Most Similar Users to User (Cosine Method) [0] are:
[Average]: 0.7774972948007628
[Accuracy]:97.73221316194464 RMSE
User[6]
User[2]
User[3]

[Pridicted missing value through Weighted Average]: 34.24915464495578
Specify the User to reveal similar Users: 0
Specify the index to pridict: 1

[3] Most Similar Users to User (Pearson method) [0] are: 
[Average]: 0.2732585303334473
[Accuracy]:96.97628421592619 RMSE
User[6]
User[2]
User[3]

[Pridicted missing value through Weighted Average]: 19.88516012925192
New model based after averaging Cosine and Pearson: 
[Accuracy]:98.57142857142857 RMSE
[[37 15  0  4 37 22 44]
 [30 40 18 18  0 11  0]
 [50  0 50  9 41 54 32]
 [20 35 41  0 18 21 41]
 [ 0 42 47 28 20 44 43]
 [28 10 28 33  0 55 12]
 [33 22 11 43 53  0 33]]

Original: 
[[34 11  0  4 37 22 44]
 [30 40 18 18  0 11  0]
 [50  0 50  9 41 54 32]
 [20 35 41  0 18 21 41]
 [ 0 42 47 28 20 44 43]
 [28 10 28 33  0 55 12]
 [

2 Similar Users

In [ ]:
#Cosine Method
user = input('Specify the User to reveal similar Users: ')
pridictedValue = input('Specify the index to pridict: ')

print('\n[2] Most Similar Users to User (Cosine Method) [' + user+'] are:')
avg = average2(sortedArr2[int(user)][1],
               sortedArr2[int(user)][2])
replaceWithW(arrCopy[int(user)], float(wAverage(user, 2, pridictedValue)), int(pridictedValue))
mse = sklearn.metrics.mean_squared_error(arr[int(user)], arrCopy[int(user)])
rmse = mt.sqrt(mse)
print('[Average]: '+str(float(avg)))
print('[Accuracy]:'+str(100 - rmse)+' RMSE')

for i in range(len(key)):
    if((i + 1) <= 2):
        print('User[' + str(key[int(user)][i + 1])+']')

print('\n[Pridicted missing value through Weighted Average]: ' +
      str(float(wAverage(user, 2, pridictedValue))))

#Pearson Method
user = input('Specify the User to reveal similar Users: ')
pridictedValue = input('Specify the index to pridict: ')
print('\n[2] Most Similar Users to User (Pearson method) [' + user+'] are: ')
avg = average2(sortedArrP2[int(user)][1],
               sortedArrP2[int(user)][2])
replaceWithW(arrCopy2[int(user)], float(pwAverage(user, 2, pridictedValue)), int(pridictedValue))
mse = sklearn.metrics.mean_squared_error(arr[int(user)], arrCopy2[int(user)])
rmse = mt.sqrt(mse)
print('[Average]: '+str(float(avg)))
print('[Accuracy]:'+str(100 - rmse)+' RMSE')

for i in range(len(pkey)):
    if((i + 1) <= 2):
        print('User[' + str(pkey[int(user)][i + 1])+']')

print('\n[Pridicted missing value through Weighted Average]: ' +
      str(float(pwAverage(user, 2, pridictedValue))))

print("New model based after averaging Cosine and Pearson: ")
mse = sklearn.metrics.mean_squared_error(arrCopy, arrCopy2)
rmse = mt.sqrt(mse)
print('[Accuracy]:'+str(100 - rmse)+' RMSE')
print(newModel(arrCopy, arrCopy2))
print("")
print("Original: ")
print(arrCopy)


Specify the User to reveal similar Users: 0
Specify the index to pridict: 0

[2] Most Similar Users to User (Cosine Method) [0] are:
[Average]: 0.8011256314560466
[Accuracy]:100.0 RMSE
User[6]
User[2]

[Pridicted missing value through Weighted Average]: 40.56950581844743
Specify the User to reveal similar Users: 0
Specify the index to pridict: 1

[2] Most Similar Users to User (Pearson method) [0] are: 
[Average]: 0.36510464352415717
[Accuracy]:98.48814210796309 RMSE
User[6]
User[2]

[Pridicted missing value through Weighted Average]: 15.99108276861883
New model based after averaging Cosine and Pearson: 
[Accuracy]:99.42857142857143 RMSE
[[40 13  0  4 37 22 44]
 [30 40 18 18  0 11  0]
 [50  0 50  9 41 54 32]
 [20 35 41  0 18 21 41]
 [ 0 42 47 28 20 44 43]
 [28 10 28 33  0 55 12]
 [33 22 11 43 53  0 33]]

Original: 
[[40 11  0  4 37 22 44]
 [30 40 18 18  0 11  0]
 [50  0 50  9 41 54 32]
 [20 35 41  0 18 21 41]
 [ 0 42 47 28 20 44 43]
 [28 10 28 33  0 55 12]
 [33 22 11 43 53  0 33]]


# Item - Item

In [ ]:
tranposedArray = arr.T

print(np.array(tranposedArray))

result2 = []
result2 = simMatrix(arrT)

presult2 = []
presult2 = PearMatrix(arrT)

print('\n Item to item cosine /n ' + str(np.array(result2)))

print('\n item to item pearson /n' + str(np.array(presult2)))

[[40 30 50 20  0 28 33]
 [11 40  0 35 42 10 22]
 [ 0 18 50 41 47 28 11]
 [ 4 18  9  0 28 33 43]
 [37  0 41 18 20  0 53]
 [22 11 54 21 44 55  0]
 [44  0 32 41 43 12 33]]

 Item to item cosine /n [[1.         0.53923388 0.67262315 0.63633282 0.81495452 0.72866156
  0.74786947]
 [0.53923388 1.         0.73232757 0.6866993  0.51546366 0.5550692
  0.71486862]
 [0.67262315 0.73232757 1.         0.62064819 0.60871935 0.89348288
  0.78231494]
 [0.63633282 0.6866993  0.62064819 1.         0.64261751 0.6281115
  0.61574797]
 [0.81495452 0.51546366 0.60871935 0.64261751 1.         0.5592227
  0.88173588]
 [0.72866156 0.5550692  0.89348288 0.6281115  0.5592227  1.
  0.73590484]
 [0.74786947 0.71486862 0.78231494 0.61574797 0.88173588 0.73590484
  1.        ]]

 item to item pearson /n[[ 1.         -0.79626252 -0.32686522 -0.25220423  0.40561127 -0.03601042
  -0.1751555 ]
 [-0.79626252  1.          0.1024628   0.08207514 -0.40505572 -0.42793845
  -0.06837858]
 [-0.32686522  0.1024628   1.         -

# Transposed Sorted Indices Matrix

In [ ]:
key2 = []
for i in result2:
    key2.append(sorted(range(len(i)), reverse=True, key=lambda k: i[k]))
key2 = np.array(key2)

pkey2 = []
for i in presult2:
    pkey2.append(sorted(range(len(i)), reverse=True, key=lambda k: i[k]))
pkey2 = np.array(pkey2)

In [ ]:
print("")
print(key2)
print("")
print(pkey2)


[[0 4 6 5 2 3 1]
 [1 2 6 3 5 0 4]
 [2 5 6 1 0 3 4]
 [3 1 4 0 5 2 6]
 [4 6 0 3 2 5 1]
 [5 2 6 0 3 4 1]
 [6 4 2 0 5 1 3]]

[[0 4 5 6 3 2 1]
 [1 2 3 6 4 5 0]
 [2 5 6 1 3 4 0]
 [3 1 4 5 2 0 6]
 [4 6 0 3 2 5 1]
 [5 2 6 0 3 4 1]
 [6 4 2 5 1 0 3]]


In [ ]:
arrCopy2 = copy.deepcopy(tranposedArray)
parrCopy2 = copy.deepcopy(tranposedArray)

4 Similar Items

In [ ]:
#Cosine Method
sortedArr3 = sortedMatrix(result2)
item = input('Specify the Item to reveal similar Item: ')
pridictedValue = input('specify the index to pridict: ')

avg = average4(sortedArr3[int(item)][1], sortedArr3[int(
    item)][2], sortedArr3[int(item)][3], sortedArr3[int(item)][4])
replaceWithW(arrCopy2[int(item)], float(wAverageI(item, 4, pridictedValue)), int(pridictedValue))
mse = sklearn.metrics.mean_squared_error(
    tranposedArray[int(item)], arrCopy2[int(item)])
rmse = mt.sqrt(mse)
print('[4] Most Similar Items to Item (Cosine Method) ['+item+'] are:')
print('[Average]: '+str(float(avg)))
print('[Accuracy]:'+str(100 - rmse)+' RMSE')
for i in range(len(key2)):
    if((i + 1) <= 4):
        print('Item[' + str(key2[int(item)][i + 1])+']')

print('\n[Weighted Average]: '+str(float(wAverageI(item, 4, pridictedValue))))

#Pearson Method
sortedArrP3 = sortedMatrix(presult2)
item = input('Specify the Item to reveal similar Item: ')
pridictedValue = input('Specify the index to pridict: ')

avg = average4(sortedArrP3[int(item)][1], sortedArrP3[int(
    item)][2], sortedArrP3[int(item)][3], sortedArrP3[int(item)][4])
replaceWithW(parrCopy2[int(item)], float(pwAverageI(item, 4, pridictedValue)), int(pridictedValue))
mse = sklearn.metrics.mean_squared_error(
    tranposedArray[int(item)], parrCopy2[int(item)])
rmse = mt.sqrt(mse)
print('[4] Most Similar Items to Item (Pearson Method) ['+item+'] are:')
print('[Average]: '+str(float(avg)))
print('[Accuracy]:'+str(100 - rmse)+' RMSE')
for i in range(len(key2)):
    if((i + 1) <= 4):
        print('Item[' + str(key2[int(item)][i + 1])+']')

print('\n[Weighted Average]: '+str(float(pwAverageI(item, 4, pridictedValue))))

print("New model based after averaging Cosine and Pearson: ")
mse = sklearn.metrics.mean_squared_error(arrCopy, arrCopy2)
rmse = mt.sqrt(mse)
print('[Accuracy]:'+str(100 - rmse)+' RMSE')
print(newModel(arrCopy2, parrCopy2))
print("")
print("Original: ")
print(arrCopy2)

Specify the Item to reveal similar Item: 0
specify the index to pridict: 0
[4] Most Similar Items to Item (Cosine Method) [0] are:
[Average]: 0.7410271765340456
[Accuracy]:94.70849737787081 RMSE
Item[4]
Item[6]
Item[5]
Item[2]

[Weighted Average]: 26.949872323224096
Specify the Item to reveal similar Item: 0
Specify the index to pridict: 1
[4] Most Similar Items to Item (Pearson Method) [0] are:
[Average]: -0.014439719849657882
[Accuracy]:95.8423907968985 RMSE
Item[4]
Item[6]
Item[5]
Item[2]

[Weighted Average]: 19.39862911898359
New model based after averaging Cosine and Pearson: 
[Accuracy]:77.6776857318576 RMSE
[[33 24 50 20  0 28 33]
 [11 40  0 35 42 10 22]
 [ 0 18 50 41 47 28 11]
 [ 4 18  9  0 28 33 43]
 [37  0 41 18 20  0 53]
 [22 11 54 21 44 55  0]
 [44  0 32 41 43 12 33]]

Original: 
[[26 30 50 20  0 28 33]
 [11 40  0 35 42 10 22]
 [ 0 18 50 41 47 28 11]
 [ 4 18  9  0 28 33 43]
 [37  0 41 18 20  0 53]
 [22 11 54 21 44 55  0]
 [44  0 32 41 43 12 33]]


3 Similar Items

In [ ]:
#Cosine Method
sortedArr3 = sortedMatrix(result2)
item = input('Specify the Item to reveal similar Item: ')
pridictedValue = input('Specify the index to pridict: ')

avg = average3(sortedArr3[int(item)][1], sortedArr3[int(
    item)][2], sortedArr3[int(item)][3])
replaceWithW(arrCopy2[int(item)], float(wAverageI(item, 3, pridictedValue)), int(pridictedValue))
mse = sklearn.metrics.mean_squared_error(
    tranposedArray[int(item)], arrCopy2[int(item)])
rmse = mt.sqrt(mse)
print('[3] Most Similar Items to Item (Cosine Method) ['+item+'] are:')
print('[Average]: '+str(float(avg)))
print('[Accuracy]:'+str(100 - rmse)+' RMSE')
for i in range(len(key2)):
    if((i + 1) <= 3):
        print('Item[' + str(key2[int(item)][i + 1])+']')

print('\n[Weighted Average]: '+str(float(wAverageI(item, 3, pridictedValue))))

#Pearson Method
sortedArrP3 = sortedMatrix(presult2)
item = input('Specify the Item to reveal similar Item: ')
pridictedValue = input('Specify the index to pridict: ')

avg = average3(sortedArrP3[int(item)][1], sortedArrP3[int(
    item)][2], sortedArrP3[int(item)][3])
replaceWithW(parrCopy2[int(item)], float(pwAverageI(item, 3, pridictedValue)), int(pridictedValue))
mse = sklearn.metrics.mean_squared_error(
    tranposedArray[int(item)], parrCopy2[int(item)])
rmse = mt.sqrt(mse)
print('[3] Most Similar Items to Item (Pearson Method) ['+item+'] are:')
print('[Average]: '+str(float(avg)))
print('[Accuracy]:'+str(100 - rmse)+' RMSE')
for i in range(len(key2)):
    if((i + 1) <= 3):
        print('Item[' + str(key2[int(item)][i + 1])+']')

print('\n[Weighted Average]: '+str(float(pwAverageI(item, 3, pridictedValue))))

print("New model based after averaging Cosine and Pearson: ")
mse = sklearn.metrics.mean_squared_error(parrCopy2, arrCopy2)
rmse = mt.sqrt(mse)
print('[Accuracy]:'+str(100 - rmse)+' RMSE')
print(newModel(arrCopy2, parrCopy2))
print("")
print("Original: ")
print(arrCopy2)


Specify the Item to reveal similar Item: 0
Specify the index to pridict: 0
[3] Most Similar Items to Item (Cosine Method) [0] are:
[Average]: 0.7638285185751498
[Accuracy]:97.73221316194464 RMSE
Item[4]
Item[6]
Item[5]

[Weighted Average]: 34.61225418856216
Specify the Item to reveal similar Item: 0
Specify the index to pridict: 1
[3] Most Similar Items to Item (Pearson Method) [0] are:
[Average]: 0.06481511605167024
[Accuracy]:95.8423907968985 RMSE
Item[4]
Item[6]
Item[5]

[Weighted Average]: 19.88516012925192
New model based after averaging Cosine and Pearson: 
[Accuracy]:98.2100051305512 RMSE
[[37 24 50 20  0 28 33]
 [11 40  0 35 42 10 22]
 [ 0 18 50 41 47 28 11]
 [ 4 18  9  0 28 33 43]
 [37  0 41 18 20  0 53]
 [22 11 54 21 44 55  0]
 [44  0 32 41 43 12 33]]

Original: 
[[34 30 50 20  0 28 33]
 [11 40  0 35 42 10 22]
 [ 0 18 50 41 47 28 11]
 [ 4 18  9  0 28 33 43]
 [37  0 41 18 20  0 53]
 [22 11 54 21 44 55  0]
 [44  0 32 41 43 12 33]]


2 Similar items

In [ ]:
#Cosine Method
sortedArr3 = sortedMatrix(result2)
item = input('Specify the Item to reveal similar Item: ')
pridictedValue = input('Specify the index to pridict: ')

avg = average2(sortedArr3[int(item)][1], sortedArr3[int(
    item)][2])
replaceWithW(arrCopy2[int(item)], float(wAverageI(item, 2, pridictedValue)), int(pridictedValue))
mse = sklearn.metrics.mean_squared_error(
    tranposedArray[int(item)], arrCopy2[int(item)])
rmse = mt.sqrt(mse)
print('[2] Most Similar Items to Item (Cosine Method) ['+item+'] are:')
print('[Average]: '+str(float(avg)))
print('[Accuracy]:'+str(100 - rmse)+' RMSE')
for i in range(len(key2)):
    if((i + 1) <= 2):
        print('Item[' + str(key2[int(item)][i + 1])+']')

print('\n[Weighted Average]: '+str(float(wAverageI(item, 2, pridictedValue))))

#Pearson Method
sortedArrP3 = sortedMatrix(presult2)
item = input('Specify the Item to reveal similar Item: ')
pridictedValue = input('Specify the index to pridict: ')

avg = average2(sortedArrP3[int(item)][1], sortedArrP3[int(
    item)][2])
replaceWithW(parrCopy2[int(item)], float(pwAverageI(item, 2, pridictedValue)), int(pridictedValue))
mse = sklearn.metrics.mean_squared_error(
    tranposedArray[int(item)], parrCopy2[int(item)])
rmse = mt.sqrt(mse)
print('[3] Most Similar Items to Item (Pearson Method) ['+item+'] are:')
print('[Average]: '+str(float(avg)))
print('[Accuracy]:'+str(100 - rmse)+' RMSE')
for i in range(len(key2)):
    if((i + 1) <= 2):
        print('Item[' + str(key2[int(item)][i + 1])+']')

print('\n[Weighted Average]: '+str(float(pwAverageI(item, 2, pridictedValue))))
print("New model based after averaging Cosine and Pearson: ")
mse = sklearn.metrics.mean_squared_error(parrCopy2, arrCopy2)
rmse = mt.sqrt(mse)
print('[Accuracy]:'+str(100 - rmse)+' RMSE')
print(newModel(arrCopy2, parrCopy2))
print("")
print("Original: ")
print(arrCopy2)


Specify the Item to reveal similar Item: 0
Specify the index to pridict: 0
[2] Most Similar Items to Item (Cosine Method) [0] are:
[Average]: 0.7814119964173027
[Accuracy]:95.8423907968985 RMSE
Item[4]
Item[6]

[Weighted Average]: 40.63337411201077
Specify the Item to reveal similar Item: 0
Specify the index to pridict: 1
[3] Most Similar Items to Item (Pearson Method) [0] are:
[Average]: 0.18480042399846705
[Accuracy]:94.3305329048616 RMSE
Item[4]
Item[6]

[Weighted Average]: 15.99108276861883
New model based after averaging Cosine and Pearson: 
[Accuracy]:99.42857142857143 RMSE
[[40 17 50 20  0 28 33]
 [11 40  0 35 42 10 22]
 [ 0 18 50 41 47 28 11]
 [ 4 18  9  0 28 33 43]
 [37  0 41 18 20  0 53]
 [22 11 54 21 44 55  0]
 [44  0 32 41 43 12 33]]

Original: 
[[40 19 50 20  0 28 33]
 [11 40  0 35 42 10 22]
 [ 0 18 50 41 47 28 11]
 [ 4 18  9  0 28 33 43]
 [37  0 41 18 20  0 53]
 [22 11 54 21 44 55  0]
 [44  0 32 41 43 12 33]]
